geekshop/adminapp/urls.py
from django.urls import path, include
from rest_framework import routers

from adminapp.views.category import *
from adminapp.views.product import *
from adminapp.views.user import *
app_name = 'adminapp'

router = routers.DefaultRouter(trailing_slash=False)
router.register('users', ShopUserViewSet)
router.register('categories', CategoryViewSet)
router.register('products', ProductsViewSet)


urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', ProductCategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', ProductReadListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('api/categories/<int:pk>/products', ProductsOfCategoryViewSet.as_view()),

    path('api/', include(router.urls))
]

geekshop/authapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import *

app_name = 'authapp'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterCreateView.as_view(), name='register'),
    path('edit/', login_required(UserEditUpdateView.as_view()), name='edit'),
    path('verify/<str:email>/<str:activation_key>/', UserVerifyView.as_view(), name='verify')

]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', IndexListView.as_view(), name='index'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from django.forms import Textarea

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CategoryUpdateForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        fields = ('name', 'description', 'is_deleted')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if not isinstance(field.widget, Textarea) and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = ProductCategory.objects.filter(is_deleted=False)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if not isinstance(field.widget, Textarea) and field.widget.input_type == 'checkbox':
                field.widget.attrs['class'] = 'form-check-input'
            if field_name == 'category':
                field.widget.attrs['type'] = 'hidden'

geekshop/adminapp/views/category.py
from django.db import connection
from django.db.models import F
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView, DeleteView
from rest_framework import viewsets
from adminapp import serializers

from adminapp.forms import CategoryCreateForm, CategoryUpdateForm
from mainapp.models import ProductCategory, Product
from .product import db_profile_by_type
from .user import IsAdminUserPassedTestMixin


class ProductCategoryCreateView(IsAdminUserPassedTestMixin, CreateView):
    model = ProductCategory
    form_class = CategoryCreateForm
    template_name = 'adminapp/category/category_create.html'
    success_url = reverse_lazy('admin_staff:categories')
    extra_context = {'title': 'категории/создать'}


class ProductCategoriesListView(IsAdminUserPassedTestMixin, ListView):
    model = ProductCategory
    template_name = 'adminapp/category/categories.html'
    extra_context = {'title': 'админка/категории'}
    context_object_name = 'objects'


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    extra_context = {'title': 'категории/изменение'}
    form_class = CategoryUpdateForm

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)


class ProductCategoryDeleteView(IsAdminUserPassedTestMixin, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category/category_delete.html'
    context_object_name = 'category_to_delete'
    extra_context = {'title': 'категории/удаление'}

    def delete(self, request, *args, **kwargs):
        _object = self.get_object()
        _object.is_deleted = True
        _object.save()

        return HttpResponseRedirect(reverse_lazy('admin_staff:categories'))


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = ProductCategory.objects.filter(is_deleted=False)
    serializer_class = serializers.CategorySerializer

    def get_queryset(self):
        if self.kwargs.get('pk'):
            self.serializer_class = serializers.ProductsSerializer
            return Product.objects.filter(category__pk=self.kwargs.get('pk'))
        else:
            return ProductCategory.objects.filter(is_deleted=False)

geekshop/adminapp/views/product.py
from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from rest_framework import viewsets, generics

from adminapp.forms import ProductEditForm
from mainapp.models import ProductCategory, Product
from .user import IsAdminUserPassedTestMixin
from .. import serializers


class ProductCreateView(IsAdminUserPassedTestMixin, CreateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/products/product_create.html'
    extra_context = {'title': "продукты/создание"}

    def get_initial(self):
        self.initial = {'category': get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))}
        return self.initial

    def get_success_url(self):
        return reverse('admin_staff:products', args=[self.request.POST.get('category')])


class ProductsListView(IsAdminUserPassedTestMixin, ListView):
    model = Product
    template_name = 'adminapp/products/products.html'
    context_object_name = 'objects'
    extra_context = {'title': 'админка/продукт'}
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk')).order_by('is_deleted', 'name')


class ProductUpdateView(IsAdminUserPassedTestMixin, UpdateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/products/product_update.html'
    extra_context = {'title': "продукты/редактирование"}

    def get_initial(self):
        _object = self.get_object()
        self.initial = {'category': _object.category}

    def get_success_url(self):
        return reverse('admin_staff:products', args=[self.request.POST.get('category')])


class ProductDeleteView(IsAdminUserPassedTestMixin, DeleteView):
    model = Product
    template_name = 'adminapp/products/product_delete.html'
    extra_context = {'title': 'продукт/удаление'}
    context_object_name = 'product_to_delete'

    def delete(self, request, *args, **kwargs):
        _object = self.get_object()
        _object.is_deleted = True
        _object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        _object = self.get_object()
        return reverse('admin_staff:products', args=[_object.category.pk])


class ProductReadListView(IsAdminUserPassedTestMixin, ListView):
    model = Product
    template_name = 'adminapp/products/product_read.html'
    context_object_name = 'product'
    extra_context = {'title': 'продукты/подробнее'}

    def get_queryset(self):
        return Product.objects.get(pk=self.kwargs.get('pk'))


class ProductsViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all().order_by('is_deleted')
    serializer_class = serializers.ProductsSerializer


class ProductsOfCategoryViewSet(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = serializers.ProductsSerializer

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk')).order_by('is_deleted', 'name')


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_productcategory_save(sender, instance, **kwargs):
    if instance.pk and not instance.is_deleted:
        instance.product_set.update(is_deleted=False)
    else:
        instance.product_set.update(is_deleted=True)

    db_profile_by_type(sender, 'UPDATE', connection.queries)

geekshop/adminapp/views/user.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from rest_framework import viewsets, permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from adminapp import serializers
from adminapp.forms import ShopUserAdminEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser


class IsAdminUserPassedTestMixin(UserPassesTestMixin):
    login_url = '/auth/login/'
    redirect_field_name = 'next'

    def test_func(self):
        return self.request.user.is_superuser


class UserCreateView(IsAdminUserPassedTestMixin, CreateView):
    model = ShopUser
    template_name = 'adminapp/user/user_create.html'
    extra_context = {'title': 'пользователи/создать'}
    form_class = ShopUserRegisterForm
    success_url = '/admin_staff/users/read/'


class UsersListView(IsAdminUserPassedTestMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/user/users.html'
    context_object_name = 'objects'
    extra_context = {'title': 'админка/пользователи'}
    paginate_by = 3
    ordering = ('is_deleted', '-is_active', '-is_superuser', '-is_staff', 'username')


class UserUpdateView(IsAdminUserPassedTestMixin, UpdateView):
    model = ShopUser
    template_name = 'adminapp/user/user_update.html'
    form_class = ShopUserAdminEditForm
    success_url = reverse_lazy('admin_staff:users')
    extra_context = {'title': 'пользователи/редактировать'}


class UserDeleteView(IsAdminUserPassedTestMixin, DeleteView):
    model = ShopUser
    template_name = 'adminapp/user/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')
    extra_context = {'title': 'пользователи/удаление'}
    context_object_name = 'user_to_delete'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ShopUserViewSet(viewsets.ModelViewSet):
    queryset = ShopUser.objects.all()
    serializer_class = serializers.ShopUserSerializer

geekshop/adminapp/templates/adminapp/user/user_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
        <form class="form-horizontal" action="{% url 'admin_staff:user_create' %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="form-control" type="submit" value="Создать">
        </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/user/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ user_to_delete.username }}
        {% if user_to_delete.first_name %}
            <b>({{ user_to_delete.first_name|title }}</b>
            {% if user_to_delete.last_name %}
                {{ user_to_delete.last_name|title }}
            {% endif %})
        {% endif %}
        ?
        <form action="{% url 'admin_staff:user_delete' user_to_delete.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_staff:users' %}" style="color: white">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
        <form class="form-horizontal" action="{% url 'admin_staff:user_update' form.instance.id %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="form-control" type="submit" value="Сохранить">
        </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/user/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Пользователи
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for user in objects %}
                                <tr {% if user.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                    <td><a href="{% url 'admin_staff:user_update' user.id %}"
                                           style="color: dodgerblue">{{ user.username }}</a></td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        {% if user.is_staff %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if user.is_active %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>{{ user.last_login }}</td>
                                    <td>
                                        <a {% if user.is_deleted %} class="invisible" {% endif %}
                                                                    href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="pagination">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>

                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:user_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}